backend:
  name: git-gateway
  branch: master
# will only use image links for now and not this
media_folder: "public/assets/articles"
public_folder: "/assets/articles"
collections:
  - name: "article"
    label: "Article"
    folder: "src/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "Author Page Link",
          name: "authorPage",
          widget: "string",
          required: false,
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["article"] }
      - {
          label: "Video Url",
          name: "videoUrl",
          widget: "string",
          required: false,
        }
      - { label: "Thumbnail", name: "image", widget: "string" }
      - {
          label: "References",
          name: "references",
          widget: "list",
          field: { label: "Reference", name: "reference", widget: "string" },
        }
      - { label: "Body", name: "body", widget: "markdown" }
